unit UnitLogin.Model;
{*******************************************************************************
    Generated By   : JsonToDelphiClass - 0.65
    Project link   : https://github.com/PKGeorgiev/Delphi-JsonToDelphiClass
    Generated On   : 2019-10-11 11:02:42

    Created By     : Petar Georgiev - (http://pgeorgiev.com)
    Adapted Web By : Marlon Nardi - (http://jsontodelphi.com)
*******************************************************************************}

interface

uses Generics.Collections, Rest.Json;

type

TUsuarios = class
private
  FLogin: String;
  FSenha: String;
public
  property login: String read FLogin write FLogin;
  property senha: String read FSenha write FSenha;
  function ToJsonString: string;
  class function FromJsonString(AJsonString: string): TUsuarios;
end;

TLogin = class
private
  FUsuarios: TArray<TUsuarios>;
public
  property Usuarios: TArray<TUsuarios> read FUsuarios write FUsuarios;
  destructor Destroy; override;
  function ToJsonString: string;
  class function FromJsonString(AJsonString: string): TLogin;
end;

implementation

{TUsuarios}


function TUsuarios.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TUsuarios.FromJsonString(AJsonString: string): TUsuarios;
begin
  result := TJson.JsonToObject<TUsuarios>(AJsonString)
end;

{TLogin}

destructor TLogin.Destroy;
var
  LUsuariosItem: TUsuarios;
begin

 for LUsuariosItem in FUsuarios do
   LUsuariosItem.Free;

  inherited;
end;

function TLogin.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TLogin.FromJsonString(AJsonString: string): TLogin;
begin
  result := TJson.JsonToObject<TLogin>(AJsonString)
end;

end.
